### PR TITLE
Dataset sweep pt1

### PR DESCRIPTION
**Pull request by GregoryJPavier**

### CODE REVIEW

**Comment by GregoryJPavier** [comment]
I have left the:
- annual-personal-wellbeing-estimates
- average-travel-time
- early-years
CSVs as they are, need some advice on which ones to keep and which ones can be deleted.

**Review by BenHowland — COMMENTED** [review]
Looks good.

**Comment by sazzadur-ons** [comment]
@GregoryJPavier You can delete/skip the 3 datasets of children-at-expected-level as these 3 datasets were merged to form early-years

**Comment by GregoryJPavier** [comment]
> @GregoryJPavier You can delete/skip the 3 datasets of children-at-expected-level as these 3 datasets were merged to form early-years

I've deleted those three datasets now.

**Pull request merged**
